package com.project.durian.services.impl;

import com.project.durian.dto.OrderDTO;
import com.project.durian.dto.ProductDTO;
import com.project.durian.model.Orders;
import com.project.durian.repository.OrderRepository;
import com.project.durian.services.OrderService;
import com.project.durian.services.ProductService;
import org.aspectj.weaver.ast.Or;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

@Service
public class OrderServiceImpl implements OrderService {

    @Autowired
    EmailService emailService;

    @Autowired
    private OrderRepository orderRepository;

    @Autowired
    private ProductService productService;

    @Override
    public List<OrderDTO> list() {
        return StreamSupport.stream(orderRepository.findAll().spliterator(), false)
                .map(OrderDTO::new)
                .collect(Collectors.toList());
    }

    @Override
    public void add(OrderDTO orderDTO) {
        ProductDTO product = productService.get(orderDTO.getProductId());
        orderDTO.setProductName(product.getName());
        product.setQuantity(product.getQuantity() - orderDTO.getQuantity());
        productService.update(product);
        //remove quantity from product


        String email = orderDTO.getEmail();
        String subject = "plz change this Bryce";
        String body = "Hello, " + orderDTO.getFirstName() + "!\n\n\n" +
                "Bryce this is not the not the type of email u get after buying a product, plz change it\n\n" +
                "we know ur location is at" + orderDTO.getPostalCode() + "\n" +
                "We will Thank you for your patience and will get back to you as soon as possible.\n" +
                "This message is an autogenerated response. Please don't reply. Thank you!";

        emailService.sendEmail(email, subject, body);

        orderRepository.save(new Orders(orderDTO));
    }
    @Override
    public OrderDTO get(Long id) {
        return new OrderDTO(orderRepository.findById(id).get());
    }

    @Override
    public void update(OrderDTO orderDTO) {
        orderRepository.save(new Orders(orderDTO));
    }

    @Override
    public void delete(Long id) {
        orderRepository.deleteById(id);
    }
}
